name: CI_Action

on:
  push:
    branches: [main, Development]
  pull_request:
    branches: [main, Development]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        cd worksheet2/my-react-app
        npm ci

    - name: Run the tests
      run: |
        cd worksheet2/my-react-app
        npm test -- --watchAll=false --ci --passWithNoTests

    - name: Build
      run: |
        cd worksheet2/my-react-app
        npm run build
